Cases
ira1988/carrot-1 pull request #21
Opened 2022-09-05 17:46 UTC by olena-semenenko

Html + Css. Images are optimazed.

2022-09-06 04:23 UTC, ira1988 requested changes

2022-09-06 04:23 UTC, ira1988 commented on index.html
> +        <h3 class="subtitle">This is what we do</h3>
давайте  h3 заміним на р

2022-09-06 04:23 UTC, ira1988 commented on index.html
> +        <div class="container">
class container моджна додати одразу на секцію щоб зайвий раз не створювати додатковий div

2022-09-06 04:23 UTC, ira1988 commented on styles/style.css
> +    font-weight: 400;
це значення за замовчуванням від браузера можна не прописувати

2022-09-06 12:08 UTC, ira1988 requested changes

2022-09-06 12:08 UTC, ira1988 commented on styles/style.css
> +.body{
видали будь-ласка крапку перед body бо в такому разі в тебе font-family не працює

2022-09-06 18:53 UTC, olena-semenenko commented on index.html
> +        <div class="container">
Ні, бо section не можна обмежувати по ширині, вона має бути безмежна. Тут категорично не згодна.

2022-09-06 18:53 UTC, olena-semenenko commented on index.html
> +        <h3 class="subtitle">This is what we do</h3>
Тут можу замінити, але по логіці макету у всіх частинах є заголовок секції, текст, що безпосередньо відноситься до нього (subtitle) та звичайний текстовий контент, який може змінюватися за потреби( такий прописують lopem10). Тому тут все ж думаю за h3, але мені не принципово.

2022-09-06 18:59 UTC, olena-semenenko commented on styles/style.css
> +    font-weight: 400;
Font-weight: 400 від браузера прописано для тега <p>. В данному випадку тут використано h3, тож з суттю коментаря не згодна. При зміні h3 на p прописувати не буду.

2022-09-06 18:59 UTC, olena-semenenko commented on styles/style.css
> +.body{
Тут не помітила)

2022-09-07 03:18 UTC, ira1988 approved these changes

2022-09-07 03:18 UTC, merged